//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfOrder.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresy
    {
        public int ID { get; set; }
        public Nullable<int> ID_Uzytkownika { get; set; }
        public string Ulica { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string Kraj { get; set; }
        public string TypAdresu { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
