//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfOrder.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KoszykProdukty
    {
        public int ID { get; set; }
        public Nullable<int> ID_Koszyka { get; set; }
        public Nullable<int> ID_Produktu { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Koszyk Koszyk { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
