//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfOrder.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelOrder : DbContext
    {
        public ModelOrder()
            : base("name=ModelOrder")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresy> Adresy { get; set; }
        public virtual DbSet<Dostawy> Dostawy { get; set; }
        public virtual DbSet<Koszyk> Koszyk { get; set; }
        public virtual DbSet<KoszykProdukty> KoszykProdukty { get; set; }
        public virtual DbSet<Opinie> Opinie { get; set; }
        public virtual DbSet<Platnosci> Platnosci { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Rabaty> Rabaty { get; set; }
        public virtual DbSet<RodzajeProduktow> RodzajeProduktow { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ulubione> Ulubione { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<ZamowieniaProdukty> ZamowieniaProdukty { get; set; }
    }
}
