//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfOrder.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosci
    {
        public int ID { get; set; }
        public Nullable<int> ID_Zamowienia { get; set; }
        public string TypPlatnosci { get; set; }
        public string StatusPlatnosci { get; set; }
    
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
